---
- name: Initialize Kubernetes control plane
  ansible.builtin.command: >
    kubeadm init
    --pod-network-cidr={{ pod_network_cidr }}
    --kubernetes-version={{ kube_version }}
    --apiserver-advertise-address={{ ansible_host }}
  register: kubeadm_init
  args:
    creates: /etc/kubernetes/admin.conf
  tags: master

- name: Extract kubeadm join command
  ansible.builtin.set_fact:
    join_command: "{{ kubeadm_init.stdout_lines
                     | select('search', 'kubeadm join')
                     | list | first }} --ignore-preflight-errors=all"
  tags: master

- name: Create .kube directory for ubuntu user
  ansible.builtin.file:
    path: /home/{{ ansible_user }}/.kube
    state: directory
    owner: "{{ ansible_user }}"
    mode: '0755'
  tags: master

- name: Copy admin.conf to user kube config
  ansible.builtin.copy:
    src: /etc/kubernetes/admin.conf
    dest: /home/{{ ansible_user }}/.kube/config
    owner: "{{ ansible_user }}"
    mode: '0644'
  tags: master

- name: Install Flannel CNI network plugin
  ansible.builtin.shell: >
    kubectl apply -f https://raw.githubusercontent.com/coreos/flannel/master/Documentation/kube-flannel.yml
  environment:
    KUBECONFIG: /etc/kubernetes/admin.conf
  tags: master
